[theme]
base = "dark"
primaryColor = "#36A7FF"
backgroundColor = "#07101D"
secondaryBackgroundColor = "#0F1C2E"
textColor = "#EEF5FF"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
